PortsClass
QString PortsClass::_port
Referenced by setPort, getPort.
QString PortsClass::_location
Referenced by setLocation, getLocation.
QString PortsClass::_description
Referenced by setDescription, getDescription.
QString PortsClass::_manufacturer
Referenced by setManufacturer, getManufacturer.
QString PortsClass::_serialNumber
Referenced by setSerialNumber, getSerialNumber.
QString PortsClass::_vendorID
Referenced by setVendorID, getVendorID.
QString PortsClass::_productID
Referenced by setProductID, getProductID.
QString PortsClass::_busyState
Referenced by setBusyState, getBusyState.
void PortsClass::setPort(QString newPort)
References _port.
Referenced by SerialComms::getComPortsEnums.
void PortsClass::setLocation(QString newLocation)
References _location.
Referenced by SerialComms::getComPortsEnums.
void PortsClass::setDescription(QString newDescription)
References _description.
Referenced by SerialComms::getComPortsEnums.
void PortsClass::setManufacturer(QString newManufacturer)
References _manufacturer.
Referenced by SerialComms::getComPortsEnums.
void PortsClass::setSerialNumber(QString newSerialNumber)
References _serialNumber.
Referenced by SerialComms::getComPortsEnums.
void PortsClass::setVendorID(QString newVendorID)
References _vendorID.
Referenced by SerialComms::getComPortsEnums.
void PortsClass::setProductID(QString newProductID)
References _productID.
Referenced by SerialComms::getComPortsEnums.
void PortsClass::setBusyState(QString newBusyState)
References _busyState.
Referenced by SerialComms::getComPortsEnums.
QString PortsClass::getPort()
References _port.
QString PortsClass::getLocation()
References _location.
QString PortsClass::getDescription()
References _description.
QString PortsClass::getManufacturer()
References _manufacturer.
QString PortsClass::getSerialNumber()
References _serialNumber.
QString PortsClass::getVendorID()
References _vendorID.
QString PortsClass::getProductID()
References _productID.
QString PortsClass::getBusyState()
References _busyState.