MeasuringInterface
Ui::MeasuringInterface* MeasuringInterface::ui
Referenced by MeasuringInterface, ~MeasuringInterface, on_drawGridCheckbox_stateChanged, on_gridSlider_sliderMoved, on_smallGridSlider_sliderMoved, on_drawScaleButton_pressed, on_removeScaleButton_pressed, on_mmSpinbox_valueChanged, updateGridSizeLabel, on_drawRulerButton_pressed, hideScaleLine, labelMouseClickedPos, on_removeRulerButton_pressed, on_clearAllRulersButton_pressed, on_updateRulersButton_pressed, labelMousePos, resizeWindowToScreenSize, resizeLabelToWindow, updateFrame, setEnableRulerOptions.
LinesClass* MeasuringInterface::_lClassObj
Referenced by MeasuringInterface, on_mmSpinbox_valueChanged, on_drawRulerButton_pressed, labelMouseClickedPos, on_removeRulerButton_pressed, on_clearAllRulersButton_pressed, on_updateRulersButton_pressed.
Mat MeasuringInterface::_workingFrame
Referenced by on_drawGridCheckbox_stateChanged, on_gridSlider_sliderMoved, on_savePlainImageButton_pressed, on_drawScaleButton_pressed, on_removeScaleButton_pressed, hideScaleLine, labelMouseClickedPos, on_removeRulerButton_pressed, on_clearAllRulersButton_pressed, on_updateRulersButton_pressed, receiveCurrentMat.
Mat MeasuringInterface::_frameWithGrid
Referenced by on_gridSlider_sliderMoved.
Mat MeasuringInterface::_frameWithScale
Referenced by labelMouseClickedPos.
Mat MeasuringInterface::_frameWithRulers
Referenced by on_saveImageWithRulersPushButton_pressed, labelMouseClickedPos, on_removeRulerButton_pressed, on_clearAllRulersButton_pressed, on_updateRulersButton_pressed.
bool MeasuringInterface::_rulerDrawingStatus
Referenced by on_drawRulerButton_pressed, labelMouseClickedPos.
bool MeasuringInterface::_scaleDrawingStatus
Referenced by on_drawScaleButton_pressed, labelMouseClickedPos.
QPoint MeasuringInterface::_tempPoint1
Referenced by labelMouseClickedPos.
QPoint MeasuringInterface::_tempPoint2
Referenced by labelMouseClickedPos.
QPixmap MeasuringInterface::_workingPixmap
Referenced by receiveCurrentMat.
int MeasuringInterface::_screenWidth
Referenced by receiveCurrentMat, resizeWindowToScreenSize.
int MeasuringInterface::_screenHeight
Referenced by receiveCurrentMat, resizeWindowToScreenSize.
int MeasuringInterface::_frameWidth
Referenced by receiveCurrentMat.
int MeasuringInterface::_frameHeight
Referenced by receiveCurrentMat.
double MeasuringInterface::_PXtoMM
Referenced by on_mmSpinbox_valueChanged, updateGridSizeLabel, labelMouseClickedPos.
QPoint MeasuringInterface::_mappedPoint1
Referenced by on_mmSpinbox_valueChanged, labelMouseClickedPos.
QPoint MeasuringInterface::_mappedPoint2
Referenced by on_mmSpinbox_valueChanged, labelMouseClickedPos.
MeasuringInterface::MeasuringInterface(QWidget *parent=nullptr)
References ui, labelMousePos, labelMouseClickedPos, sendTableObject, _lClassObj, removeRulerAtIndex, removeAllRulers, attachTableRulerText.
MeasuringInterface::~MeasuringInterface()
References ui.
void MeasuringInterface::receiveCurrentMat(Mat currentFrame, QSize frameRes, QRect screenSize)
References _workingFrame, _workingPixmap, matToPixmap, _screenWidth, _screenHeight, _frameWidth, _frameHeight, updateFrame, resizeWindowToScreenSize, resizeLabelToWindow.
void MeasuringInterface::labelMousePos(QPoint &pos)
References ui.
Referenced by MeasuringInterface.
void MeasuringInterface::labelMouseClickedPos(QPoint &pos)
References _rulerDrawingStatus, ui, _tempPoint1, _tempPoint2, LinesClass::calculateLenghtOfLine, _frameWithRulers, _workingFrame, _lClassObj, LinesClass::addRuler, _PXtoMM, sendTableObject, updateFrame, _scaleDrawingStatus, _mappedPoint1, HelperClass::map, _mappedPoint2, _frameWithScale, LinesClass::calculatePXtoMM, setEnableRulerOptions.
Referenced by MeasuringInterface.
void MeasuringInterface::sendTableObject(QTableView &listView)
Referenced by MeasuringInterface, on_mmSpinbox_valueChanged, labelMouseClickedPos, on_removeRulerButton_pressed, on_clearAllRulersButton_pressed, on_updateRulersButton_pressed.
void MeasuringInterface::removeRulerAtIndex(int rowIndex)
Referenced by MeasuringInterface, on_removeRulerButton_pressed.
void MeasuringInterface::removeAllRulers()
Referenced by MeasuringInterface, on_clearAllRulersButton_pressed.
void MeasuringInterface::attachTableRulerText(Mat *frameToDrawOn)
Referenced by MeasuringInterface, on_saveImageWithRulersPushButton_pressed.
void MeasuringInterface::on_savePlainImageButton_pressed()
References _workingFrame.
void MeasuringInterface::on_drawGridCheckbox_stateChanged(int arg1)
References ui, on_gridSlider_sliderMoved, hideScaleLine, updateFrame, _workingFrame.
void MeasuringInterface::on_gridSlider_sliderMoved(int position)
References ui, _frameWithGrid, _workingFrame, HelperClass::placeGrid, updateGridSizeLabel, updateFrame.
Referenced by on_drawGridCheckbox_stateChanged, on_smallGridSlider_sliderMoved.
void MeasuringInterface::on_drawScaleButton_pressed()
References ui, updateFrame, _workingFrame, setEnableRulerOptions, _scaleDrawingStatus.
void MeasuringInterface::on_removeScaleButton_pressed()
References updateFrame, _workingFrame, ui.
void MeasuringInterface::on_mmSpinbox_valueChanged(int arg1)
References _PXtoMM, LinesClass::calculatePXtoMM, _mappedPoint1, _mappedPoint2, updateGridSizeLabel, ui, _lClassObj, LinesClass::setNewPxToMM, sendTableObject.
void MeasuringInterface::on_smallGridSlider_sliderMoved(int position)
References on_gridSlider_sliderMoved, ui.
void MeasuringInterface::on_drawRulerButton_pressed()
References _lClassObj, LinesClass::countRulers, ui, _rulerDrawingStatus, hideScaleLine.
void MeasuringInterface::on_removeRulerButton_pressed()
References ui, _frameWithRulers, _workingFrame, removeRulerAtIndex, sendTableObject, _lClassObj, LinesClass::reDrawRulers, updateFrame.
void MeasuringInterface::on_clearAllRulersButton_pressed()
References Errors::clearAllRulersErrorWindow, _frameWithRulers, _workingFrame, removeAllRulers, sendTableObject, ui, _lClassObj, LinesClass::reDrawRulers, updateFrame.
void MeasuringInterface::on_updateRulersButton_pressed()
References _frameWithRulers, _workingFrame, sendTableObject, ui, _lClassObj, LinesClass::reDrawRulers, updateFrame.
Referenced by on_saveImageWithRulersPushButton_pressed.
void MeasuringInterface::on_saveImageWithRulersPushButton_pressed()
References on_updateRulersButton_pressed, _frameWithRulers, attachTableRulerText.
QPixmap MeasuringInterface::matToPixmap(Mat frame)
Referenced by receiveCurrentMat, updateFrame.
void MeasuringInterface::resizeWindowToScreenSize()
References _screenWidth, ui, _screenHeight.
Referenced by receiveCurrentMat.
void MeasuringInterface::resizeLabelToWindow()
References ui.
Referenced by receiveCurrentMat.
void MeasuringInterface::updateFrame(Mat newFrame)
References ui, matToPixmap.
Referenced by on_drawGridCheckbox_stateChanged, on_gridSlider_sliderMoved, on_drawScaleButton_pressed, on_removeScaleButton_pressed, hideScaleLine, labelMouseClickedPos, on_removeRulerButton_pressed, on_clearAllRulersButton_pressed, on_updateRulersButton_pressed, receiveCurrentMat.
void MeasuringInterface::drawLine()
void MeasuringInterface::clickedLabel(QMouseEvent *event)
void MeasuringInterface::updateGridSizeLabel(int val)
References ui, _PXtoMM.
Referenced by on_gridSlider_sliderMoved, on_mmSpinbox_valueChanged.
void MeasuringInterface::hideScaleLine()
References ui, updateFrame, _workingFrame.
Referenced by on_drawGridCheckbox_stateChanged, on_drawRulerButton_pressed.
void MeasuringInterface::setEnableRulerOptions(bool state)
References ui.
Referenced by on_drawScaleButton_pressed, labelMouseClickedPos.