SerialComms
QSerialPort* SerialComms::_serial
Referenced by SerialComms, ~SerialComms, initSerialComms, connectToSerial, disconnectSerial, serialIsConnected, receiveData, sendData.
QList<PortsClass> SerialComms::_availablePorts
Referenced by getComPortsEnums, connectToSerial, serialIsConnected, getSerialEnumerations.
SerialComms::SerialComms()
References _serial.
SerialComms::~SerialComms()
References _serial.
void SerialComms::connectToSerial(QString vendorID, QString productID)
References getComPortsEnums, _serial, _availablePorts, initSerialComms, Errors::serialConnectionError, Errors::serialIsAlreadyConnected.
Referenced by MainWindow::on_actionEnumerate_Ports_triggered, MainWindow::on_actionAttempt_to_connect_triggered, MainWindow::init.
void SerialComms::disconnectSerial()
References _serial.
Referenced by MainWindow::on_actionDisconnect_Serial_triggered.
QList< QString > SerialComms::getSerialEnumerations()
References getComPortsEnums, _availablePorts.
Referenced by MainWindow::on_actionEnumerate_Ports_triggered, serialIsConnected.
int SerialComms::serialIsConnected(QString vendorID, QString productID)
References getSerialEnumerations, _availablePorts, _serial.
Referenced by MainWindow::on_positionCalibrationButton_pressed, MainWindow::on_actionEnumerate_Ports_triggered, MainWindow::on_actionAttempt_to_connect_triggered, MainWindow::on_actionCheck_connection_status_triggered, MainWindow::init, MainWindow::drawCalibrationLines.
QByteArray SerialComms::receiveData()
References _serial.
int SerialComms::sendData(const QByteArray &data)
References _serial.
Referenced by MainWindow::on_gantryUpButton_pressed, MainWindow::on_gantryDownButton_pressed, MainWindow::on_gantryLeftButton_pressed, MainWindow::on_gantryRightButton_pressed, MainWindow::on_ringLightOnButton_pressed, MainWindow::on_ringLightOffButton_pressed, MainWindow::on_ringLeftUpBut_pressed, MainWindow::on_ringLeftDownBut_pressed, MainWindow::on_ringRightUpBut_pressed, MainWindow::on_ringRightDownBut_pressed.
int SerialComms::initSerialComms(QString portNumber)
References _serial.
Referenced by connectToSerial.
void SerialComms::getComPortsEnums()
References _availablePorts, PortsClass::setPort, PortsClass::setLocation, PortsClass::setDescription, PortsClass::setManufacturer, PortsClass::setSerialNumber, PortsClass::setVendorID, PortsClass::setProductID, PortsClass::setBusyState.
Referenced by connectToSerial, getSerialEnumerations.