UserSettings
void UserSettings::saveSettings(const QString &key, const QVariant &value, const QString &group)
References Errors::fatalError.
Referenced by MainWindow::saveGUISettings, StartupDialog::saveSettings.
QVariant UserSettings::loadSettings(const QString &key, const QVariant &defaultValue, const QString &group)
Referenced by MainWindow::loadGUISettings, StartupDialog::loadSettings.