HelperClass
void HelperClass::placeGrid(Mat &frame, int distance)
Referenced by MeasuringInterface::on_gridSlider_sliderMoved.
int HelperClass::map(const int x, const int in_min, const int in_max, const int out_min, const int out_max)
Referenced by LinesClass::addRuler, MeasuringInterface::labelMouseClickedPos.