StartupDialog
Ui::StartupDialog* StartupDialog::ui
Referenced by StartupDialog, ~StartupDialog, loadSettings, saveSettings, flushSettings, on_buttonBox_accepted.
StartupDialog::StartupDialog(QWidget *parent=nullptr)
References ui, loadSettings.
StartupDialog::~StartupDialog()
References ui.
void StartupDialog::sendData(unsigned int val, QString param)
Referenced by flushSettings, on_buttonBox_accepted.
void StartupDialog::on_buttonBox_rejected()
References Errors::fatalError.
void StartupDialog::on_StartupDialog_finished(int result)
References flushSettings, saveSettings.
void StartupDialog::on_buttonBox_accepted()
References ui, sendData, Errors::fatalError.
void StartupDialog::on_StartupDialog_rejected()
References Errors::fatalError.
void StartupDialog::loadSettings()
References UserSettings::loadSettings, GROUP_LOCATION, ui.
Referenced by StartupDialog.
void StartupDialog::saveSettings()
References UserSettings::saveSettings, ui, GROUP_LOCATION.
Referenced by on_StartupDialog_finished.
void StartupDialog::flushSettings()
References sendData, ui.
Referenced by on_StartupDialog_finished.