MainWindow
Ui::MainWindow* MainWindow::ui
Referenced by on_focusButton_pressed, defaultUIVals, on_modeButton_pressed, on_positionCalibrationButton_pressed, setOptionsButtons, setMeasurementButtons, on_actionFull_screen_triggered, on_contrastOptionsBtn_pressed, on_brightnessOptionsBtn_pressed, on_saturationOptionsBtn_pressed, on_zoomOptionsBtn_pressed, on_focusOptionsBtn_pressed, on_measureButton_pressed, on_captureButton_pressed, on_distortionButton_pressed, on_gantryUpButton_pressed, on_gantryDownButton_pressed, on_gantryLeftButton_pressed, on_gantryRightButton_pressed, on_actionRe_Establish_the_connection_triggered, init, resizeWindowToScreenSize, resizeLabelToWindow, captureImage, loadGUISettings, saveGUISettings, setRingLighGUI, switchAlgToGantry, MainWindow, ~MainWindow.
StartupDialog* MainWindow::_startUpDialog
Referenced by MainWindow.
MeasuringInterface* MainWindow::_measuringInterface
Referenced by on_measureButton_pressed, init.
QScreen* MainWindow::_screen
QRect MainWindow::_screenGeometry
Referenced by on_measureButton_pressed, resizeWindowToScreenSize, centerWindow.
QTimer MainWindow::_videoFPSTimer
Referenced by on_modeButton_pressed, on_positionCalibrationButton_pressed, init, ~MainWindow.
SerialComms MainWindow::_ardSerial
Referenced by on_positionCalibrationButton_pressed, on_actionEnumerate_Ports_triggered, on_actionAttempt_to_connect_triggered, on_actionCheck_connection_status_triggered, on_gantryUpButton_pressed, on_gantryDownButton_pressed, on_gantryLeftButton_pressed, on_gantryRightButton_pressed, on_ringLightOnButton_pressed, on_ringLightOffButton_pressed, on_ringLeftUpBut_pressed, on_ringLeftDownBut_pressed, on_ringRightUpBut_pressed, on_ringRightDownBut_pressed, on_actionDisconnect_Serial_triggered, init, drawCalibrationLines.
Camera MainWindow::_camObj
Referenced by on_focusButton_pressed, defaultCamOpt, on_contrastSlider_sliderMoved, on_brightnessSlider_sliderMoved, on_saturationSlider_sliderMoved, on_zoomSlider_sliderMoved, on_focusSlider_sliderMoved, on_contrastOptionsBtn_pressed, on_brightnessOptionsBtn_pressed, on_saturationOptionsBtn_pressed, on_zoomOptionsBtn_pressed, on_focusOptionsBtn_pressed, on_measureButton_pressed, on_distortionButton_pressed, init, captureImage, loadGUISettings, ~MainWindow.
Options MainWindow::_usrOptions
Mat MainWindow::_globalFrame
Referenced by captureImage.
QPixmap MainWindow::_globalQPixmap
Referenced by captureImage.
int MainWindow::_camPort
Referenced by init, receiveData.
bool MainWindow::_savePreferences
Referenced by init, receiveData, ~MainWindow.
bool MainWindow::_fullScreen
Referenced by init, centerWindow, receiveData.
int MainWindow::_res_Width
Referenced by on_measureButton_pressed, on_distortionButton_pressed, init, captureImage, receiveData.
int MainWindow::_res_Height
Referenced by on_measureButton_pressed, init, receiveData.
int MainWindow::_fps
Referenced by init, receiveData.
bool MainWindow::_calibrationInProgress
Referenced by on_positionCalibrationButton_pressed, captureImage.
bool MainWindow::_liveLensCorrection
Referenced by on_lensCorrectioncheckBox_stateChanged, init, captureImage, loadGUISettings.
MainWindow::MainWindow(QWidget *parent=nullptr)
References _startUpDialog, receiveData, ui, init.
MainWindow::~MainWindow()
References _camObj, Camera::releaseCamera, _videoFPSTimer, _savePreferences, saveGUISettings, ui.
void MainWindow::init()
References switchAlgToGantry, ui, _fullScreen, resizeWindowToScreenSize, resizeLabelToWindow, centerWindow, _camObj, Camera::cameraInit, _camPort, _fps, _res_Width, _res_Height, Errors::fatalError, Camera::getFPS, _videoFPSTimer, captureImage, sendGlobalMat, _measuringInterface, _savePreferences, loadGUISettings, _liveLensCorrection, _ardSerial, SerialComms::connectToSerial, ARDUINO_VENDOR_ID, ARDUINO_PRODUCT_ID, SerialComms::serialIsConnected, setRingLighGUI.
Referenced by MainWindow.
void MainWindow::receiveData(unsigned int val, QString param)
References _camPort, _res_Width, _res_Height, _fps, _fullScreen, _savePreferences.
Referenced by MainWindow.
void MainWindow::sendOffsets(unsigned int arg, int val)
void MainWindow::sendGlobalMat(Mat currentFrame, QSize frameRes, QRect screenSize)
Referenced by on_measureButton_pressed, init.
void MainWindow::captureImage()
References _globalFrame, _camObj, Camera::captureFrameMat, _calibrationInProgress, _globalQPixmap, Camera::convertMatToQPixmap, drawCalibrationLines, ui, _liveLensCorrection, Camera::retrieveGlobalUndistortedFrame, _res_Width.
Referenced by on_captureButton_pressed, init.
void MainWindow::on_focusButton_pressed()
References ui, _camObj, Camera::setParam.
void MainWindow::on_actionFull_screen_triggered(bool checked)
References ui, resizeLabelToWindow.
void MainWindow::on_actionCenter_window_triggered()
References centerWindow.
void MainWindow::on_actionSet_to_defaults_triggered()
References defaultCamOpt, defaultUIVals.
void MainWindow::on_modeButton_pressed()
References ui, _videoFPSTimer, setMeasurementButtons, Errors::cameraPositionUncalibrated, on_positionCalibrationButton_pressed.
void MainWindow::on_positionCalibrationButton_pressed()
References ui, _ardSerial, SerialComms::serialIsConnected, ARDUINO_VENDOR_ID, ARDUINO_PRODUCT_ID, Errors::serialConnectionError, setOptionsButtons, switchAlgToGantry, _videoFPSTimer, setMeasurementButtons, _calibrationInProgress.
Referenced by on_modeButton_pressed.
void MainWindow::on_focusSlider_sliderMoved(int position)
References _camObj, Camera::setParam.
void MainWindow::on_zoomSlider_sliderMoved(int position)
References _camObj, Camera::setParam.
void MainWindow::on_saturationSlider_sliderMoved(int position)
References _camObj, Camera::setParam.
void MainWindow::on_brightnessSlider_sliderMoved(int position)
References _camObj, Camera::setParam.
void MainWindow::on_contrastSlider_sliderMoved(int position)
References _camObj, Camera::setParam.
void MainWindow::on_contrastOptionsBtn_pressed()
References _camObj, Camera::setParam, ui.
void MainWindow::on_brightnessOptionsBtn_pressed()
References _camObj, Camera::setParam, ui.
void MainWindow::on_saturationOptionsBtn_pressed()
References _camObj, Camera::setParam, ui.
void MainWindow::on_zoomOptionsBtn_pressed()
References _camObj, Camera::setParam, ui.
void MainWindow::on_focusOptionsBtn_pressed()
References _camObj, Camera::setParam, ui.
void MainWindow::on_captureButton_pressed()
References captureImage, ui.
void MainWindow::on_measureButton_pressed()
References ui, sendGlobalMat, _camObj, Camera::retrieveGlobalFrame, _res_Width, _res_Height, _screenGeometry, Camera::retrieveGlobalUndistortedFrame, _measuringInterface.
void MainWindow::on_distortionButton_pressed()
References _camObj, Camera::retrieveGlobalUndistortedFrame, _res_Width, ui, Camera::convertMatToQPixmap.
void MainWindow::on_lensCorrectioncheckBox_stateChanged(int arg1)
References _liveLensCorrection.
void MainWindow::on_actionEnumerate_Ports_triggered()
References _ardSerial, SerialComms::getSerialEnumerations, SerialComms::serialIsConnected, ARDUINO_VENDOR_ID, ARDUINO_PRODUCT_ID, SerialComms::connectToSerial, Errors::serialNoEnumsFound.
void MainWindow::on_actionAttempt_to_connect_triggered()
References _ardSerial, SerialComms::connectToSerial, ARDUINO_VENDOR_ID, ARDUINO_PRODUCT_ID, SerialComms::serialIsConnected, Errors::serialNoEnumsFound.
void MainWindow::setRingLighGUI(bool state)
References ui.
Referenced by init, drawCalibrationLines.
void MainWindow::on_actionCheck_connection_status_triggered()
References _ardSerial, SerialComms::serialIsConnected, ARDUINO_VENDOR_ID, ARDUINO_PRODUCT_ID.
void MainWindow::on_gantryUpButton_pressed()
References ui, _ardSerial, SerialComms::sendData.
void MainWindow::on_gantryDownButton_pressed()
References ui, _ardSerial, SerialComms::sendData.
void MainWindow::on_gantryLeftButton_pressed()
References ui, _ardSerial, SerialComms::sendData.
void MainWindow::on_gantryRightButton_pressed()
References ui, _ardSerial, SerialComms::sendData.
void MainWindow::on_ringLightOnButton_pressed()
References _ardSerial, SerialComms::sendData.
void MainWindow::on_ringLightOffButton_pressed()
References _ardSerial, SerialComms::sendData.
void MainWindow::on_ringLeftUpBut_pressed()
References _ardSerial, SerialComms::sendData.
void MainWindow::on_ringLeftDownBut_pressed()
References _ardSerial, SerialComms::sendData.
void MainWindow::on_ringRightUpBut_pressed()
References _ardSerial, SerialComms::sendData.
void MainWindow::on_ringRightDownBut_pressed()
References _ardSerial, SerialComms::sendData.
void MainWindow::on_actionDisconnect_Serial_triggered()
References _ardSerial, SerialComms::disconnectSerial.
void MainWindow::on_actionRe_Establish_the_connection_triggered()
References ui.
void MainWindow::resizeWindowToScreenSize()
References _screenGeometry, ui.
Referenced by init.
void MainWindow::resizeLabelToWindow()
References ui.
Referenced by on_actionFull_screen_triggered, init.
void MainWindow::centerWindow()
References _fullScreen, _screenGeometry.
Referenced by on_actionCenter_window_triggered, init.
void MainWindow::loadGUISettings()
References UserSettings::loadSettings, GROUP_LOCATION, ui, _camObj, Camera::setParam, _liveLensCorrection.
Referenced by init.
void MainWindow::saveGUISettings()
References UserSettings::saveSettings, ui, GROUP_LOCATION.
Referenced by ~MainWindow.
void MainWindow::defaultCamOpt()
References _camObj, Camera::setParam.
Referenced by on_actionSet_to_defaults_triggered.
void MainWindow::defaultUIVals()
References ui.
Referenced by on_actionSet_to_defaults_triggered.
void MainWindow::setOptionsButtons(bool val)
References ui.
Referenced by on_positionCalibrationButton_pressed.
void MainWindow::setMeasurementButtons(bool val)
References ui.
Referenced by on_modeButton_pressed, on_positionCalibrationButton_pressed.
void MainWindow::drawCalibrationLines(QPixmap *frameToDrawOn)
References _ardSerial, SerialComms::serialIsConnected, ARDUINO_VENDOR_ID, ARDUINO_PRODUCT_ID, setRingLighGUI, Errors::fatalError.
Referenced by captureImage.
void MainWindow::listenToKeyPress(QKeyEvent *event)
void MainWindow::switchAlgToGantry(bool state)
References ui.
Referenced by on_positionCalibrationButton_pressed, init.