Camera
VideoCapture* Camera::_cameraObj
Referenced by cameraInit, setParam, getParam, captureFrameMat, setBufferSize, releaseCamera.
Mat Camera::_currentFrameMat
Referenced by captureFrameMat, retrieveGlobalFrame, retrieveGlobalUndistortedFrame.
Mat Camera::_currentFrameMatAdjustedColor
Referenced by convertMatToQPixmap.
Mat Camera::_correctedMat
Referenced by retrieveGlobalUndistortedFrame.
const Mat Camera::_cameraMatrix
Referenced by retrieveGlobalUndistortedFrame.
const Mat Camera::_distortionCoefficients
Referenced by retrieveGlobalUndistortedFrame.
int Camera::cameraInit(const int camera, const int fps, const int &width, const int &height)
References _cameraObj, Errors::cameraOpenErrorWindow, setParam.
Referenced by MainWindow::init.
void Camera::setParam(VideoCaptureProperties param, int value)
References _cameraObj.
Referenced by cameraInit, MainWindow::on_focusButton_pressed, MainWindow::defaultCamOpt, MainWindow::on_contrastSlider_sliderMoved, MainWindow::on_brightnessSlider_sliderMoved, MainWindow::on_saturationSlider_sliderMoved, MainWindow::on_zoomSlider_sliderMoved, MainWindow::on_focusSlider_sliderMoved, MainWindow::on_contrastOptionsBtn_pressed, MainWindow::on_brightnessOptionsBtn_pressed, MainWindow::on_saturationOptionsBtn_pressed, MainWindow::on_zoomOptionsBtn_pressed, MainWindow::on_focusOptionsBtn_pressed, MainWindow::loadGUISettings.
unsigned char Camera::getParam(cv::VideoCaptureProperties param)
References _cameraObj.
Referenced by getFPS.
void Camera::setBufferSize(int frames)
References _cameraObj.
Mat Camera::captureFrameMat()
References _cameraObj, _currentFrameMat.
Referenced by MainWindow::captureImage.
QPixmap Camera::convertMatToQPixmap(Mat &frameToConver)
References _currentFrameMatAdjustedColor.
Referenced by MainWindow::on_distortionButton_pressed, MainWindow::captureImage.
unsigned char Camera::getFPS()
References getParam.
Referenced by MainWindow::init.
Mat Camera::retrieveGlobalFrame()
References _currentFrameMat.
Referenced by MainWindow::on_measureButton_pressed.
Mat Camera::retrieveGlobalUndistortedFrame(int width)
References _cameraMatrix, _currentFrameMat, _correctedMat, _distortionCoefficients.
Referenced by MainWindow::on_measureButton_pressed, MainWindow::on_distortionButton_pressed, MainWindow::captureImage.
void Camera::releaseCamera()
References _cameraObj.
Referenced by MainWindow::~MainWindow.
QImage Camera::Mat2QImage(cv::Mat const &src)