Errors
Q_NORETURN void Errors::fatalError(QString errorMessage)
Referenced by cameraOpenErrorWindow, cameraPositionUncalibrated, clearAllRulersErrorWindow, MainWindow::init, MainWindow::drawCalibrationLines, StartupDialog::on_buttonBox_rejected, StartupDialog::on_buttonBox_accepted, StartupDialog::on_StartupDialog_rejected, UserSettings::saveSettings.
void Errors::cameraOpenErrorWindow()
References fatalError.
Referenced by Camera::cameraInit.
int Errors::clearAllRulersErrorWindow()
References fatalError.
Referenced by MeasuringInterface::on_clearAllRulersButton_pressed.
int Errors::cameraPositionUncalibrated()
References fatalError.
Referenced by MainWindow::on_modeButton_pressed.
void Errors::serialConnectionError()
Referenced by MainWindow::on_positionCalibrationButton_pressed, SerialComms::connectToSerial.
void Errors::serialIsAlreadyConnected()
Referenced by SerialComms::connectToSerial.
void Errors::serialNoEnumsFound()
Referenced by MainWindow::on_actionEnumerate_Ports_triggered, MainWindow::on_actionAttempt_to_connect_triggered.