LinesClass
double LinesClass::_PXtoMM
Referenced by addRuler, receiveTableObject, setNewPxToMM, addTableRulerText.
QList<Ruler> LinesClass::_rulersList
Referenced by addRuler, reDrawRulers, receiveTableObject, removeRuler, removeRulers, addTableRulerText, countRulers.
bool LinesClass::_lineGuard
Referenced by LinesClass.
int LinesClass::_currentState
Referenced by LinesClass.
QPoint LinesClass::_tempPoint1
Referenced by addRuler.
QPoint LinesClass::_tempPoint2
Referenced by addRuler.
QPoint LinesClass::_scaledPoint1
Referenced by addRuler.
QPoint LinesClass::_scaledPoint2
Referenced by addRuler.
QStringList LinesClass::_tableHeader
Referenced by LinesClass, receiveTableObject.
QStandardItemModel* LinesClass::_tableModel
Referenced by LinesClass, receiveTableObject, addTableRulerText.
QList<QStandardItem> LinesClass::_items
LinesClass::LinesClass()
LinesClass::LinesClass /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////.
References _lineGuard, _currentState, _tableHeader, _tableModel.
void LinesClass::addRuler(Mat &drawingMat, QPoint _tempPoint1, QPoint _tempPoint2, QSize frameSize, QSize matSize, double pxToMMRatio)
References _PXtoMM, _scaledPoint1, HelperClass::map, _tempPoint1, _scaledPoint2, _tempPoint2, _rulersList, reDrawRulers.
Referenced by MeasuringInterface::labelMouseClickedPos.
void LinesClass::reDrawRulers(Mat &frameMat)
References _rulersList.
Referenced by addRuler, MeasuringInterface::on_removeRulerButton_pressed, MeasuringInterface::on_clearAllRulersButton_pressed, MeasuringInterface::on_updateRulersButton_pressed.
void LinesClass::setNewPxToMM(double pixToMMRatio)
References _PXtoMM.
Referenced by MeasuringInterface::on_mmSpinbox_valueChanged.
int LinesClass::countRulers()
References _rulersList.
Referenced by MeasuringInterface::on_drawRulerButton_pressed.
double LinesClass::calculatePXtoMM(const QPoint p1, const QPoint p2, int distance)
References calculateLenghtOfLine.
Referenced by MeasuringInterface::on_mmSpinbox_valueChanged, MeasuringInterface::labelMouseClickedPos.
double LinesClass::calculateLenghtOfLine(const QPoint p1, const QPoint p2)
Referenced by calculatePXtoMM, receiveTableObject, addTableRulerText, MeasuringInterface::labelMouseClickedPos.
void LinesClass::receiveTableObject(QTableView &tableView)
References _tableModel, _rulersList, calculateLenghtOfLine, _PXtoMM, _tableHeader.
void LinesClass::removeRuler(int rowIndex)
References _rulersList.
void LinesClass::removeRulers()
References _rulersList.
void LinesClass::addTableRulerText(Mat *frameToDrawOn)
References _tableModel, calculateLenghtOfLine, _rulersList, _PXtoMM.