opencvcalibration.cpp
_CRT_SECURE_NO_WARNINGS
@0
static void help()
Referenced by main.
static void read(const FileNode &node, Settings &x, const Settings &default_value=Settings())
References Settings::read.
bool runCalibrationAndSave(Settings &s, Size imageSize, Mat &cameraMatrix, Mat &distCoeffs, vector< vector< Point2f > > imagePoints)
References runCalibration, saveCameraParams.
Referenced by main.
int main(int argc, char *argv[])
References help, Settings::inputType, Settings::IMAGE_LIST, CAPTURING, DETECTION, runCalibrationAndSave, CALIBRATED, Settings::CHESSBOARD, Settings::CIRCLES_GRID, Settings::ASYMMETRIC_CIRCLES_GRID.
static double computeReprojectionErrors(const vector< vector< Point3f > > &objectPoints, const vector< vector< Point2f > > &imagePoints, const vector< Mat > &rvecs, const vector< Mat > &tvecs, const Mat &cameraMatrix, const Mat &distCoeffs, vector< float > &perViewErrors)
Referenced by runCalibration.
static void calcBoardCornerPositions(Size boardSize, float squareSize, vector< Point3f > &corners, Settings::Pattern patternType)
References Settings::CHESSBOARD, Settings::CIRCLES_GRID, Settings::ASYMMETRIC_CIRCLES_GRID.
Referenced by runCalibration.
static bool runCalibration(Settings &s, Size &imageSize, Mat &cameraMatrix, Mat &distCoeffs, vector< vector< Point2f > > imagePoints, vector< Mat > &rvecs, vector< Mat > &tvecs, vector< float > &reprojErrs, double &totalAvgErr)
References Settings::flag, calcBoardCornerPositions, Settings::boardSize, Settings::squareSize, Settings::calibrationPattern, computeReprojectionErrors.
Referenced by runCalibrationAndSave.
static void saveCameraParams(Settings &s, Size &imageSize, Mat &cameraMatrix, Mat &distCoeffs, const vector< Mat > &rvecs, const vector< Mat > &tvecs, const vector< float > &reprojErrs, const vector< vector< Point2f > > &imagePoints, double totalAvgErr)
References Settings::outputFileName, Settings::boardSize, Settings::squareSize, Settings::flag, Settings::aspectRatio.
Referenced by runCalibrationAndSave.